name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Create .npmrc file
        run: |
          echo "supabase.cli.skip=true" > .npmrc
          echo "legacy-peer-deps=true" >> .npmrc

      - name: Install dependencies
        run: npm ci
        env:
          NPM_CONFIG_SUPABASE_CLI_SKIP: "true"

      - name: Run format check
        run: npm run lint:format

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run type-check

      - name: Run tests
        run: npm run test
